name: Deploy Python Flask App to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t my-dockerhub-username/my-python-app:latest .

      - name: Log in again
        run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Push Docker image
        run: docker push my-dockerhub-username/my-python-app:latest
             

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Sync ArgoCD
      run: |
        argocd app sync my-python-app
        argocd app wait my-python-app --health